name: mb_website
description: Mohammed Babelly's personal portfolio.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Animation & Styling
  
  cupertino_icons: ^1.0.0

  google_fonts: ^1.1.1

  animated_text_kit: ^3.1.0

  flutter_awesome_alert_box: ^1.0.1

  flutter_animator: ^2.1.0

  auto_animated: ^2.1.0

  simple_animations: ^2.4.2

  slimy_card: ^1.0.4

  animate_icons: ^1.0.0

  timelines: ^0.0.2+1

  hover_effect: ^0.6.0

  font_awesome_flutter: ^8.12.0


  #Logic

  get: ^3.24.0

  qlevar_router: ^0.2.2

  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
    # - assets/images/